---
title: "Gregory Forsberg"
output: html_document
---

## Introduction

Hello, my name is Gregory Forsberg from Saint Paul, Minnesota. I'm currently a Senior at Macalester College, majoring in Data Science, minoring in biology. My interest lies at the intersection of data science and healthcare, where I explore how data-driven insights can transform and improve patient care and medical research.

## Contact Information

-   **Email:** [GregoryForsbergiii\@gmail.com](mailto:GregoryForsbergiii@gmail.com)
-   **Github:** <https://github.com/Gforsber>
-   **Linkedin:** <https://www.linkedin.com/in/gregory-forsberg>

## Education

**Macalester College** — St. Paul, MN  
*B.A. in Data Science, Minor in Biology*: September 2022 – May 2026

**Danish Institute of Study Abroad (DIS)** — Copenhagen, Denmark: January - May 2025

## Technical Skills

- **Programming:** R, Python, SQL  
- **Data Analysis:** Regression, survey analysis, clustering, fairness analysis  
- **Visualization:** ggplot2, Plotly, R Markdown, Shiny  
- **Tools:** Git, GitHub, Quarto, LaTeX

## Experience

**University of Iowa Biostatistics Summer Program (ISIB)** \| 2024

## Awards

**Macalester College Datafest** \| Best Research Focus \| 2024

## Active Projects

**Emergency Department Wait Times & Equity Analysis**  
Data Science Honors Project  
- Analyzed national emergency department wait time data using NHAMCS and CMS datasets  
- Apply queueing theory, regression modeling, and fairness analysis to examine disparities in care  

